name: Publish to NPM

on:
  push:
    tags:
      - 'v*'

permissions:
  id-token: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          show-progress: false

      - uses: actions/setup-node@v6
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: Build
        run: |
          npm i
          npm run build

      - name: Publish with OIDC
        run: |
          echo "registry=https://registry.npmjs.org/" > "$NPM_CONFIG_USERCONFIG"
          unset NODE_AUTH_TOKEN
          npm publish --provenance --access public